# permissions to do viewer foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foo-viewer-role
rules:
- apiGroups:
  - samplecontroller.k8s.io
  resources:
  - foos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - samplecontroller.k8s.io
  resources:
  - foos/status
  verbs:
  - get
